# 파일 읽고 쓰기

## 파일 생성하기

In [43]:
# 파일 생성하기

f = open("new_file.txt", 'w')
f.write("Hi")
f.close() # 파일을 열고나서 작업후 꼭 파일을 닫아 줘야 한다.

### 파일 열기 옵션

<li> r : 읽기모드 </li>
<li> w : 쓰기모드 </li>
<li> a : 추가모드 (append의 약자)</li>
<li> r+ : 읽기 또는 쓰기</li>
<li> w+ : 쓰기 또는 읽기</li>
<li> a+ : 추가모드 또는 읽기</li>

<br>

**r이 붙은 모드는 파일이 없으면 에러, w, a는 파일이 없으면 생성한다.**

<br>

**옵션 : 텍스트 파일 t, 바이너리 파일 b(그림, 동영상파일 등등 binary 파일)**

<br>
파일을 읽을때 파일이 깨질 수 있으므로 적절한 인코딩 옵션을 줘야한다.

In [44]:
# 읽기 모드

f = open("new_file.txt", 'r', encoding='utf-8')

msg = f.read()
print(msg)

f.close()

Hi

In [45]:
# 쓰기 모드

f = open("new_file.txt", 'w')

f.write("Hello") # 파일에 내용이 있다면 내용을 지우고 다시 쓴다.

f.close()

In [46]:
# 추가 모드

f = open("new_file.txt", "a")

f.write(" Python") # 파일의 끝에 내용을 이어쓴다.

f.close()

### r+, w+, a+ 옵션의 차이점

In [47]:
f = open("new_file.txt", "r+", encoding='utf-8') # 읽기 기능은 r옵션과 같음
f.write("Bye..") #기존 내용을 덮어 쓴다
msg = f.read() # 커서 위치에 의해 쓴 내용 이후부터 읽음
print(msg)
f.close()

 Python

In [48]:
f = open("new_file.txt", "w+", encoding='utf-8')

f.write("Life is short")
msg = f.read() 
print(msg) # 커서 위치에 의해 아무내용도 출력되지 않음

f.close()

In [49]:
f = open("new_file.txt", "a+", encoding='utf-8')

f.write(" Very sad....")
msg = f.read() 
print(msg) # 커서 위치에 의해 아무내용도 출력되지 않음

f.close()

### 읽는 파일의 커서위치에 관한 함수


<li>seek() </li>
<li>tell() </li>

In [18]:
f = open("new_file.txt", "w+", encoding='utf-8')

f.write("Life is short") # 문자열 내용을 쓴 후 커서가 파일의 끝에 위치함
cursor = f.tell()
print(cursor)

f.seek(0) # 커서를 파일의 맨 처음위치로 옮겨 준다.

msg = f.read()  
print(msg) # 파일 내용이 출력

f.close()

13
Life is short

### 외부 프로그램을 읽는 여러가지 방법

In [19]:
# 한줄만 읽기

f = open("test.txt", "r", encoding = 'utf-8')
line = f.readline()
print(line)
f.close()

1

In [20]:
# 전체 읽기

f = open("test.txt", "r", encoding = 'utf-8')

while True:
    line = f.readline()
    
    if not line:
        break
        
    print(line, end="")
f.close()

1
2
3
4
5
6

In [21]:
# readlines() 함수

f = open("test.txt", "r", encoding = 'utf-8')

lines = f.readlines()
print(lines)

for i in lines:
    i.strip() # 개행문자 제거
    print(i, end="")

['1\n', '2\n', '3\n', '4\n', '5\n', '6']
1
2
3
4
5
6

In [2]:
# csv 파일 읽기 응용

dic = {} 

total = [0,0,0]


with open("traffic.csv", 'r', encoding = 'euc-kr') as f:
    line = f.readlines()

    for i, item in enumerate(line):
        if i > 0:
            tmp = item.strip().split(',') # ',' 단위로 나뉘어 있는 한줄의 요소를 tmp리스트에 저장
            
            if tmp[0] + '년' not in dic: # 0000년 이라는 key가 존재하지 않으면 생성
                dic[tmp[0] + '년'] = {}
            
            dic[tmp[0] + '년'][tmp[1] + '월'] = {'발생건수' : tmp[2], '사망자수' : tmp[3], '부상자수' : tmp[4]} # 반복문을 돌면서 딕셔너리 생성
        
for i in dic: #딕셔너리 출력
    for j in dic[i]:
        print("%s %s " %(i ,j), end="")
        print(dic[i][j])
    print("-"*80)

2005년 1월 {'발생건수': '15494 ', '사망자수': '504 ', '부상자수': '25413'}
2005년 2월 {'발생건수': '13244 ', '사망자수': '431 ', '부상자수': '21635'}
2005년 3월 {'발생건수': '16580 ', '사망자수': '477 ', '부상자수': '25550'}
2005년 4월 {'발생건수': '17817 ', '사망자수': '507 ', '부상자수': '28131'}
2005년 5월 {'발생건수': '19085 ', '사망자수': '571 ', '부상자수': '29808'}
2005년 6월 {'발생건수': '18092 ', '사망자수': '476 ', '부상자수': '28594'}
2005년 7월 {'발생건수': '18675 ', '사망자수': '528 ', '부상자수': '29984'}
2005년 8월 {'발생건수': '19035 ', '사망자수': '562 ', '부상자수': '31603'}
2005년 9월 {'발생건수': '18759 ', '사망자수': '577 ', '부상자수': '29831'}
2005년 10월 {'발생건수': '19757 ', '사망자수': '639 ', '부상자수': '31597'}
2005년 11월 {'발생건수': '19129 ', '사망자수': '574 ', '부상자수': '30337'}
2005년 12월 {'발생건수': '18504 ', '사망자수': '530 ', '부상자수': '29750'}
--------------------------------------------------------------------------------
2006년 1월 {'발생건수': '14971 ', '사망자수': '420 ', '부상자수': '24533'}
2006년 2월 {'발생건수': '14270 ', '사망자수': '373 ', '부상자수': '22903'}
2006년 3월 {'발생건수': '16767 ', '사망자수': '465 ', '부상자수': '26013'}
2006년 4월 {'발생건수': '17948 ', '사망자수': '469 ', '부상자수': '28725'}
2006년 5월 {'발생건수': '19140 ', '사망자수': '531 ', '부상자수': '30279'}
2006년 6월 {'발생건수': '17435 ', '사망자수': '455 ', '부상자수': '27032'}
2006년 7월 {'발생건수': '18634 ', '사망자수': '516 ', '부상자수': '29978'}
2006년 8월 {'발생건수': '18794 ', '사망자수': '585 ', '부상자수': '30882'}
2006년 9월 {'발생건수': '19293 ', '사망자수': '580 ', '부상자수': '30186'}
2006년 10월 {'발생건수': '19100 ', '사망자수': '651 ', '부상자수': '30715'}
2006년 11월 {'발생건수': '19877 ', '사망자수': '701 ', '부상자수': '31270'}
2006년 12월 {'발생건수': '17516 ', '사망자수': '581 ', '부상자수': '27713'}
--------------------------------------------------------------------------------
2007년 1월 {'발생건수': '14914 ', '사망자수': '468 ', '부상자수': '23975'}
2007년 2월 {'발생건수': '14696 ', '사망자수': '446 ', '부상자수': '23717'}
2007년 3월 {'발생건수': '18166 ', '사망자수': '476 ', '부상자수': '28811'}
2007년 4월 {'발생건수': '18055 ', '사망자수': '460 ', '부상자수': '28555'}
2007년 5월 {'발생건수': '19264 ', '사망자수': '516 ', '부상자수': '30532'}
2007년 6월 {'발생건수': '18310 ', '사망자수': '538 ', '부상자수': '28662'}
2007년 7월 {'발생건수': '18037 ', '사망자수': '503 ', '부상자수': '28676'}
2007년 8월 {'발생건수': '17982 ', '사망자수': '512 ', '부상자수': '29711'}
2007년 9월 {'발생건수': '18506 ', '사망자수': '532 ', '부상자수': '29583'}
2007년 10월 {'발생건수': '19026 ', '사망자수': '582 ', '부상자수': '29802'}
2007년 11월 {'발생건수': '17815 ', '사망자수': '565 ', '부상자수': '27674'}
2007년 12월 {'발생건수': '16891 ', '사망자수': '568 ', '부상자수': '26208'}
--------------------------------------------------------------------------------
2008년 1월 {'발생건수': '14741 ', '사망자수': '444 ', '부상자수': '23522'}
2008년 2월 {'발생건수': '14176 ', '사망자수': '428 ', '부상자수': '23282'}
2008년 3월 {'발생건수': '16752 ', '사망자수': '502 ', '부상자수': '26284'}
2008년 4월 {'발생건수': '17498 ', '사망자수': '476 ', '부상자수': '27364'}
2008년 5월 {'발생건수': '19515 ', '사망자수': '493 ', '부상자수': '30935'}
2008년 6월 {'발생건수': '18824 ', '사망자수': '423 ', '부상자수': '28872'}
2008년 7월 {'발생건수': '19562 ', '사망자수': '452 ', '부상자수': '30553'}
2008년 8월 {'발생건수': '18545 ', '사망자수': '529 ', '부상자수': '29705'}
2008년 9월 {'발생건수': '18023 ', '사망자수': '502 ', '부상자수': '27894'}
2008년 10월 {'발생건수': '19926 ', '사망자수': '574 ', '부상자수': '30882'}
2008년 11월 {'발생건수': '19597 ', '사망자수': '528 ', '부상자수': '30585'}
2008년 12월 {'발생건수': '18663 ', '사망자수': '519 ', '부상자수': '29084'}
--------------------------------------------------------------------------------
2009년 1월 {'발생건수': '16532 ', '사망자수': '475 ', '부상자수': '27373'}
2009년 2월 {'발생건수': '15502 ', '사망자수': '405 ', '부상자수': '24429'}
2009년 3월 {'발생건수': '18224 ', '사망자수': '468 ', '부상자수': '27967'}
2009년 4월 {'발생건수': '19153 ', '사망자수': '439 ', '부상자수': '29521'}
2009년 5월 {'발생건수': '20237 ', '사망자수': '519 ', '부상자수': '31743'}
2009년 6월 {'발생건수': '19249 ', '사망자수': '433 ', '부상자수': '29084'}
2009년 7월 {'발생건수': '20281 ', '사망자수': '454 ', '부상자수': '31545'}
2009년 8월 {'발생건수': '19993 ', '사망자수': '514 ', '부상자수': '32200'}
2009년 9월 {'발생건수': '21004 ', '사망자수': '500 ', '부상자수': '31700'}
2009년 10월 {'발생건수': '21440 ', '사망자수': '592 ', '부상자수': '33255'}
2009년 11월 {'발생건수': '20156 ', '사망자수': '522 ', '부상자수': '31062'}
2009년 12월 {'발생건수': '20219 ', '사망자수': '517 ', '부상자수': '31996'}
--------------------------------------------------------------------------------
2010년 1월 {'발생건수': '17124 ', '사망자수': '438 ', '부상자수': '27655'}
2010년 2월 {'발생건수': '15803 ', '사망자수': '406 ', '부상자수': '24968'}
2010년 3월 {'발생건수': '17801 ', '사망자수': '396 ', '부상자수': '27350'}
2010년 4월 {'발생건수': '18386 ', '사망자수': '395 ', '부상자수': '28191'}
2010년 5월 {'발생건수': '20372 ', '사망자수': '447 ', '부상자수': '31521'}
2010년 6월 {'발생건수': '18910 ', '사망자수': '474 ', '부상자수': '28311'}
2010년 7월 {'발생건수': '18965 ', '사망자수': '453 ', '부상자수': '29577'}
2010년 8월 {'발생건수': '19383 ', '사망자수': '410 ', '부상자수': '31032'}
2010년 9월 {'발생건수': '19439 ', '사망자수': '436 ', '부상자수': '30470'}
2010년 10월 {'발생건수': '21575 ', '사망자수': '619 ', '부상자수': '33282'}
2010년 11월 {'발생건수': '20271 ', '사망자수': '541 ', '부상자수': '30907'}
2010년 12월 {'발생건수': '18849 ', '사망자수': '490 ', '부상자수': '29194'}
--------------------------------------------------------------------------------
2011년 1월 {'발생건수': '16454 ', '사망자수': '395 ', '부상자수': '25611'}
2011년 2월 {'발생건수': '14208 ', '사망자수': '339 ', '부상자수': '22493'}
2011년 3월 {'발생건수': '16832 ', '사망자수': '338 ', '부상자수': '25371'}
2011년 4월 {'발생건수': '18570 ', '사망자수': '429 ', '부상자수': '28534'}
2011년 5월 {'발생건수': '19414 ', '사망자수': '393 ', '부상자수': '29906'}
2011년 6월 {'발생건수': '18505 ', '사망자수': '415 ', '부상자수': '28469'}
2011년 7월 {'발생건수': '19253 ', '사망자수': '462 ', '부상자수': '29576'}
2011년 8월 {'발생건수': '18896 ', '사망자수': '472 ', '부상자수': '30034'}
2011년 9월 {'발생건수': '19065 ', '사망자수': '474 ', '부상자수': '29055'}
2011년 10월 {'발생건수': '20952 ', '사망자수': '520 ', '부상자수': '32133'}
2011년 11월 {'발생건수': '20283 ', '사망자수': '514 ', '부상자수': '30917'}
2011년 12월 {'발생건수': '19279 ', '사망자수': '478 ', '부상자수': '29292'}
--------------------------------------------------------------------------------
2012년 1월 {'발생건수': '16818 ', '사망자수': '418 ', '부상자수': '26281'}
2012년 2월 {'발생건수': '16656 ', '사망자수': '393 ', '부상자수': '25998'}
2012년 3월 {'발생건수': '18255 ', '사망자수': '403 ', '부상자수': '27899'}
2012년 4월 {'발생건수': '19372 ', '사망자수': '483 ', '부상자수': '29628'}
2012년 5월 {'발생건수': '19672 ', '사망자수': '444 ', '부상자수': '30163'}
2012년 6월 {'발생건수': '18854 ', '사망자수': '476 ', '부상자수': '28314'}
2012년 7월 {'발생건수': '19333 ', '사망자수': '416 ', '부상자수': '29642'}
2012년 8월 {'발생건수': '18407 ', '사망자수': '409 ', '부상자수': '29051'}
2012년 9월 {'발생건수': '19234 ', '사망자수': '486 ', '부상자수': '29462'}
2012년 10월 {'발생건수': '19557 ', '사망자수': '533 ', '부상자수': '29759'}
2012년 11월 {'발생건수': '19750 ', '사망자수': '508 ', '부상자수': '30054'}
2012년 12월 {'발생건수': '17748 ', '사망자수': '423 ', '부상자수': '28314'}
--------------------------------------------------------------------------------
2013년 1월 {'발생건수': '16016 ', '사망자수': '389 ', '부상자수': '25094'}
2013년 2월 {'발생건수': '14187 ', '사망자수': '335 ', '부상자수': '22255'}
2013년 3월 {'발생건수': '17465 ', '사망자수': '409 ', '부상자수': '26461'}
2013년 4월 {'발생건수': '18031 ', '사망자수': '380 ', '부상자수': '27795'}
2013년 5월 {'발생건수': '19686 ', '사망자수': '420 ', '부상자수': '29676'}
2013년 6월 {'발생건수': '18329 ', '사망자수': '436 ', '부상자수': '27673'}
2013년 7월 {'발생건수': '18441 ', '사망자수': '444 ', '부상자수': '28387'}
2013년 8월 {'발생건수': '18691 ', '사망자수': '412 ', '부상자수': '29190'}
2013년 9월 {'발생건수': '17806 ', '사망자수': '430 ', '부상자수': '26938'}
2013년 10월 {'발생건수': '19797 ', '사망자수': '499 ', '부상자수': '29507'}
2013년 11월 {'발생건수': '19396 ', '사망자수': '479 ', '부상자수': '28986'}
2013년 12월 {'발생건수': '17509 ', '사망자수': '459 ', '부상자수': '26749'}
--------------------------------------------------------------------------------
2014년 1월 {'발생건수': '15905 ', '사망자수': '389 ', '부상자수': '24328'}
2014년 2월 {'발생건수': '14061 ', '사망자수': '325 ', '부상자수': '21501'}
2014년 3월 {'발생건수': '18420 ', '사망자수': '358 ', '부상자수': '27714'}
2014년 4월 {'발생건수': '18443 ', '사망자수': '341 ', '부상자수': '27323'}
2014년 5월 {'발생건수': '20314 ', '사망자수': '398 ', '부상자수': '30684'}
2014년 6월 {'발생건수': '18530 ', '사망자수': '367 ', '부상자수': '27740'}
2014년 7월 {'발생건수': '19649 ', '사망자수': '407 ', '부상자수': '29596'}
2014년 8월 {'발생건수': '19603 ', '사망자수': '359 ', '부상자수': '30633'}
2014년 9월 {'발생건수': '19243 ', '사망자수': '445 ', '부상자수': '29052'}
2014년 10월 {'발생건수': '20760 ', '사망자수': '470 ', '부상자수': '31199'}
2014년 11월 {'발생건수': '19872 ', '사망자수': '476 ', '부상자수': '29525'}
2014년 12월 {'발생건수': '18752 ', '사망자수': '427 ', '부상자수': '28202'}
--------------------------------------------------------------------------------
2015년 1월 {'발생건수': '16902 ', '사망자수': '381 ', '부상자수': '25887'}
2015년 2월 {'발생건수': '14939 ', '사망자수': '296 ', '부상자수': '22999'}
2015년 3월 {'발생건수': '18616 ', '사망자수': '378 ', '부상자수': '27921'}
2015년 4월 {'발생건수': '19386 ', '사망자수': '354 ', '부상자수': '29431'}
2015년 5월 {'발생건수': '20543 ', '사망자수': '389 ', '부상자수': '31264'}
2015년 6월 {'발생건수': '18649 ', '사망자수': '390 ', '부상자수': '27469'}
2015년 7월 {'발생건수': '20278 ', '사망자수': '359 ', '부상자수': '30409'}
2015년 8월 {'발생건수': '19864 ', '사망자수': '405 ', '부상자수': '30618'}
2015년 9월 {'발생건수': '20811 ', '사망자수': '387 ', '부상자수': '31256'}
2015년 10월 {'발생건수': '21587 ', '사망자수': '470 ', '부상자수': '32436'}
2015년 11월 {'발생건수': '21170 ', '사망자수': '410 ', '부상자수': '31773'}
2015년 12월 {'발생건수': '19290 ', '사망자수': '402 ', '부상자수': '28937'}
--------------------------------------------------------------------------------
2016년 1월 {'발생건수': '17067 ', '사망자수': '336 ', '부상자수': '26323'}
2016년 2월 {'발생건수': '15664 ', '사망자수': '292 ', '부상자수': '24021'}
2016년 3월 {'발생건수': '17946 ', '사망자수': '310 ', '부상자수': '26609'}
2016년 4월 {'발생건수': '19452 ', '사망자수': '353 ', '부상자수': '29216'}
2016년 5월 {'발생건수': '19554 ', '사망자수': '347 ', '부상자수': '29172'}
2016년 6월 {'발생건수': '17977 ', '사망자수': '321 ', '부상자수': '26668'}
2016년 7월 {'발생건수': '18955 ', '사망자수': '358 ', '부상자수': '28586'}
2016년 8월 {'발생건수': '18398 ', '사망자수': '336 ', '부상자수': '28017'}
2016년 9월 {'발생건수': '17883 ', '사망자수': '375 ', '부상자수': '26761'}
2016년 10월 {'발생건수': '19918 ', '사망자수': '440 ', '부상자수': '29635'}
2016년 11월 {'발생건수': '19234 ', '사망자수': '416 ', '부상자수': '28520'}
2016년 12월 {'발생건수': '18869 ', '사망자수': '408 ', '부상자수': '28192'}
--------------------------------------------------------------------------------
2017년 1월 {'발생건수': '16970 ', '사망자수': '353 ', '부상자수': '26099'}
2017년 2월 {'발생건수': '14832 ', '사망자수': '280 ', '부상자수': '22323'}
2017년 3월 {'발생건수': '17047 ', '사망자수': '295 ', '부상자수': '25046'}
2017년 4월 {'발생건수': '17717 ', '사망자수': '293 ', '부상자수': '26530'}
2017년 5월 {'발생건수': '18502 ', '사망자수': '366 ', '부상자수': '27268'}
2017년 6월 {'발생건수': '18047 ', '사망자수': '315 ', '부상자수': '26454'}
2017년 7월 {'발생건수': '18158 ', '사망자수': '357 ', '부상자수': '27362'}
2017년 8월 {'발생건수': '18682 ', '사망자수': '353 ', '부상자수': '28162'}
2017년 9월 {'발생건수': '19891 ', '사망자수': '419 ', '부상자수': '29371'}
2017년 10월 {'발생건수': '18863 ', '사망자수': '420 ', '부상자수': '28698'}
2017년 11월 {'발생건수': '19377 ', '사망자수': '379 ', '부상자수': '28472'}
2017년 12월 {'발생건수': '18249 ', '사망자수': '355 ', '부상자수': '27044'}
--------------------------------------------------------------------------------
2018년 1월 {'발생건수': '17026 ', '사망자수': '304 ', '부상자수': '25438'}
2018년 2월 {'발생건수': '16208 ', '사망자수': '275 ', '부상자수': '24630'}
2018년 3월 {'발생건수': '17022 ', '사망자수': '310 ', '부상자수': '25015'}
2018년 4월 {'발생건수': '17992 ', '사망자수': '303 ', '부상자수': '26643'}
2018년 5월 {'발생건수': '18636 ', '사망자수': '309 ', '부상자수': '27834'}
2018년 6월 {'발생건수': '18082 ', '사망자수': '266 ', '부상자수': '26574'}
2018년 7월 {'발생건수': '18699 ', '사망자수': '315 ', '부상자수': '28104'}
2018년 8월 {'발생건수': '18335 ', '사망자수': '357 ', '부상자수': '27749'}
2018년 9월 {'발생건수': '18371 ', '사망자수': '348 ', '부상자수': '27751'}
2018년 10월 {'발생건수': '19738 ', '사망자수': '373 ', '부상자수': '28836'}
2018년 11월 {'발생건수': '19029 ', '사망자수': '298 ', '부상자수': '28000'}
2018년 12월 {'발생건수': '18010 ', '사망자수': '323 ', '부상자수': '26463'}
--------------------------------------------------------------------------------